### ISSUE TITLE
DatabaseReference.listen(callback) not working in firebase-admin 4.0.0

### ISSUE THREAD

**Issue by Malik056** [firebase/firebase-admin-python#426]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Catalina version 10.15.3
  * Firebase SDK version: N/A
  * Library version: 4.0.0
  * Firebase Product: realtime database

### [REQUIRED] Step 3: Describe the problem

I am writing a python script that listen to the changes in firebase realtime database. The DatabaseReference.listen was working fine with firebase-admin-3.2.1 but when i updated the version of firebase-admin-3.2.1 to firebase-admin-4.0.0, the DatabaseReference.listen stopped working. It raises following exception:

```
Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/LatestSoundTranslation/main.py", line 105, in <module>
    ref.listen(on_value_change)
  File "/Users/apple/PycharmProjects/LatestSoundTranslation/venv/lib/python3.7/site-packages/firebase_admin/db.py", line 376, in listen
    session = _sseclient.KeepAuthSession(self._client.credential)
AttributeError: '_Client' object has no attribute 'credential'
```

#### Steps to reproduce:

Install latest firebase-admin package using `pip install firebase-admin==4.0.0`

```
cred = credentials.Certificate('./google-services.json')
default_app = firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://your-project-id.firebaseio.com/'
})
ref = db.reference().child("any_node")
ref.listen(on_value_change)

```

#### Relevant Code:

```
def on_value_change(response):
    print(response)

cred = credentials.Certificate('./project39172648d8c7.json')
default_app = firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://speechtranslate-40b4d.firebaseio.com/'
})
ref = db.reference().child("any_node')
ref.listen(on_value_change)
```

**Comment by hiranya911** [comment]
This has been fixed in #418. Next release will include the fix.
